# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sucursal.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sucursal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esucursal.proto\x12\x08sucursal\"Q\n\x0fSucursalRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\x0c\n\x04\x66oto\x18\x04 \x01(\t\"4\n\x10SucursalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2[\n\x0fSucursalService\x12H\n\x0fValidarYGuardar\x12\x19.sucursal.SucursalRequest\x1a\x1a.sucursal.SucursalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sucursal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUCURSALREQUEST']._serialized_start=28
  _globals['_SUCURSALREQUEST']._serialized_end=109
  _globals['_SUCURSALRESPONSE']._serialized_start=111
  _globals['_SUCURSALRESPONSE']._serialized_end=163
  _globals['_SUCURSALSERVICE']._serialized_start=165
  _globals['_SUCURSALSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
